### ISSUE TITLE
Generated movefile is poor readable

### ISSUE THREAD

**Issue by miya0001** [vccw-team/wp-cli-scaffold-movefile#2]
People can't understand where we should edit.

```
local:
  vhost: http://vccw.dev
  wordpress_path: /var/www/wordpress
  database:
    name: wordpress
    user: wordpress
    password: wordpress
    host: localhost
    charset: utf8
production:
  vhost: http://vccw.dev
  wordpress_path: /var/www/wordpress/
  database:
    name: wordpress
    user: wordpress
    password: wordpress
    host: localhost
    port: 3308
    mysqldump_options: --max_allowed_packet=50MB
    charset: utf8
  exclude:
    - .git/
    - .gitignore
    - .sass-cache/
    - bin/
    - 'tmp/*'
    - 'Gemfile*'
    - Movefile
    - wp-config.php
    - 'wp-content/*.sql'
  ssh:
    host: vccw.dev
    user: vagrant
```
